on:
  push:
    branches:
      - dev

jobs:
  PushPoemToWife:
    runs-on: ubuntu-latest
    env:
     MYURL: ${{ secrets.SERVERCHAN_MY_SEND_URL }}
     WIFEURL: ${{ secrets.SERVERCHAN_WIFE_SEND_URL }}
    steps:
      - name: checkout
        uses: actions/checkout@v3
        with:
          ref: master

      - uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Send poem
        run:  |
          ls -al
          python resolve.py $MYURL $WIFEURL